#!/bin/bash
# Fix validation directory paths in Gong agent tests
# Generated by CS-Ascension 4-Agent Swarm Analysis

echo "🔧 Fixing Gong validation directory paths..."

# Fix directory references in all test files
find . -name "test_*.py" -type f -exec sed -i.bak 's/call_salesforce/gong_call1/g' {} \;
find . -name "test_*.py" -type f -exec sed -i.bak 's/emails_salesforce/gong_emails/g' {} \;

# Fix any validation framework files
find . -name "*validation*.py" -type f -exec sed -i.bak 's/call_salesforce/gong_call1/g' {} \;
find . -name "*validation*.py" -type f -exec sed -i.bak 's/emails_salesforce/gong_emails/g' {} \;

echo "✅ Directory paths updated!"
echo ""
echo "📋 Files modified:"
find . -name "*.py.bak" -type f | sed 's/.bak$//' | sort | uniq

echo ""
echo "🗑️ Cleaning up backup files..."
find . -name "*.py.bak" -type f -delete

echo ""
echo "✅ Validation path fix complete!"
echo ""
echo "You can now run validation tests with:"
echo "  python -m pytest app_backend/agent_tools/gong/tests/"
echo "  python run_full_validation.py"